---

- hosts: Routers
  gather_facts: no
  connection: local

  tasks:
  - name: Show run
    ios_command:
     commands:
       - show ip interface brief
    register: ipbrief

  - debug: var=ipbrief.stdout_lines
