---

- hosts: Routers
  connection: network_cli
  gather_facts: false

  tasks:
  - name: Add users cli #by command
    ios_config:
     lines:
      - username krzys privilege 15 secret cisco1
      - username maciek privilege 15 secret cisco2
      - username adam privilege 15 secret cisco3
      - username ola privilege 15 secret cisco4
  - name: Show users
    ios_command:
     commands:
      - show running-config | i user
    register: user
  - debug: var=user.stdout_lines

  - name: Save running-config
    ios_config:
     save_when: modified

  - name: Compare startup to running-config
    ios_config:
     diff_against: startup
    diff: true
    register: diff
